name = "builder"

[[parents]]
group = "default"

[[prefixes]]
prefix = "[参展选手] "
priority = 1

[[permissions]]
permission = "area_control.commands.claim"
value = true

[[permissions]]
permission = "area_control.commands.build"
value = true

[[permissions]]
permission = "spark.all"
value = true

[[permissions]]
permission = "command.spark"
value = true

[[permissions]]
permission = "command.spark.args"
value = true

[[permissions]]
permission = "worldedit.*"
value = true

[[permissions]]
permission = "command.tp"
value = true

[[permissions]]
permission = "command.tp.*"
value = true

[[permissions]]
permission = "command.gamemode"
value = true

[[permissions]]
permission = "command.gamemode.*"
value = true

[[permissions]]
permission = "command.ecliptic"
value = true

[[permissions]]
permission = "command.areacontrol.safe"
value = true

[[permissions]]
permission = "command.areacontrol.safe.clear"
value = true

[[permissions]]
permission = "command.easy_npc"
value = true

[[permissions]]
permission = "command.inkcraft.start"
value = true

[[permissions]]
permission = "command.inkcraft"
value = true

[[permissions]]
permission = "areacontrol.command"
value = true
