name = "internal"

[[parents]]
group = "default"

[[permissions]]
permission = "command.tp"
value = true

[[permissions]]
permission = "command.tp.*"
value = true

[[permissions]]
permission = "command.gamemode"
value = true

[[permissions]]
permission = "command.gamemode.*"
value = true
